### ISSUE TITLE
Atualizar Documento de Visão

### ISSUE THREAD

**Issue by msfernandes** [msfernandes/busine.me#27]
> Evitar exageros como: “O Busine.me espera alavancar o desenvolvimento do transporte publico como um meio de transporte mais econômico e amigável ambientalmente e, com isto, contribuir para a mobilidade urbana e o desenvolvimento das cidades.”

**Comment by wiltonsr** [comment]
Done

**Comment by msfernandes** [comment]
o cara é muito bom hausuhsauha
