### ISSUE TITLE
Atualizar diagrama de casos de uso

### ISSUE THREAD

**Issue by msfernandes** [msfernandes/busine.me#29]
> Adaptar o nome Parser de Dados para o padrão VerboNoInfinitivo PLUS substantivo.
> 
> Descrever, em linhas gerais, o diagrama de casos de uso.

**Comment by msfernandes** [comment]
Acho que o UC Favoritar Linha podia ter um include do Visualizar Linha e, talvez, Publicar Post nao seja um extend de Visualizar Linha

**Comment by wiltonsr** [comment]
O UC Favoritar Linha não precisa do include, pois o usuário vai poder apenas favoritar a linha na página de resultados da buscar sem visualizar a linha. No caso do Publicar Post, o usuário precisará visualizar a linha, então terá um <<include>> de Publicar post para Visualizar linha. O UC Parser de Dados será alterado para "Popular Banco" para atender ao padrão solicitado pela professora.
