### ISSUE TITLE
Atualizar glossário

### ISSUE THREAD

**Issue by msfernandes** [msfernandes/busine.me#33]
> O glossário está muito simples. Nesse artefato, cabem termos do domínio, termos mais técnicos, siglas, referências para fundamentar melhor o significado de cada termo apresentado.

**Comment by msfernandes** [comment]
> O glossário está muito simples. Nesse artefato, cabem termos do domínio, termos mais técnicos, siglas, referências para fundamentar melhor o significado de cada termo apresentado.

**Comment by wiltonsr** [comment]
Vou aumentar o escopo do nosso glossário e inclusive dividi lo por letras para facilitar a busca dos termos.

**Comment by wiltonsr** [comment]
Done
