### ISSUE TITLE
Criar Plano de Iteração

### ISSUE THREAD

**Issue by msfernandes** [msfernandes/busine.me#4]

**Comment by chocoelho** [comment]
Sucesso :)

Em sexta-feira, 28 de agosto de 2015, Matheus Souza Fernandes <
notifications@github.com> escreveu:

> Closed #4 https://github.com/msfernandes/busine.me/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/msfernandes/busine.me/issues/4#event-395100435.

## 

Carlos Oliveira
LAPPIS - UnB/FGA(https://lappis.unb.br/)
GitHub: @carloshfoliveira https://github.com/carloshfoliveira
LinkedIn: @carloshenriquef https://br.linkedin.com/in/carloshenriquef
